[tool.poetry]
name = "pipu"
version = "0.0.1"
description = "Find the out-dated packages installed by the pip tool and update them."
authors = ["Abeautifulsnow"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.2"
orjson = "^3.7.11"
prettytable = "^3.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
